name: socket_server
description: "Socket Server Flutter App with data persistence"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  intl: 0.20.2
  provider: ^6.1.5+1
  web_socket_channel: ^3.0.3
  flutter_libserialport: ^0.6.0
  xterm: ^4.0.0
  flutter_pty: ^0.4.2
  drift: ^2.28.1
  sqlite3: ^2.7.6
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
